# canary deployment (10% of traffic)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-server-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-server
      version: canary  # This should match the labels defined in the template
  template:
    metadata:
      labels:
        app: mlops-server
        version: canary
    spec:
      containers:
      - name: mlops-server
        image: mlops-server:0.2.0